name: Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter_version: 'stable'  

    - name: Install dependencies
      run: flutter pub get
      working-directory: aplicativo_movil

    - name: Analyze code
      run: |
        flutter analyze > analysis_result.txt
      working-directory: aplicativo_movil

    - name: Run tests
      run: |
        flutter test --machine | tojunit --output tests.xml
      working-directory: aplicativo_movil
      continue-on-error: true

    - name: Generate HTML Report
      run: |
        tojunit tests.xml > test_report.html
        echo '<h1>Analysis Report</h1><pre>' > analysis_report.html
        cat analysis_result.txt >> analysis_report.html
        echo '</pre>' >> analysis_report.html
      working-directory: aplicativo_movil

    - name: Upload Reports
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: |
          aplicativo_movil/test_report.html
          aplicativo_movil/analysis_report.html
