name: Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter_version: 'stable'  

    - name: Navigate to aplicativo_movil directory
      run: cd aplicativo_movil

    - name: Install dependencies
      run: flutter pub get
      working-directory: aplicativo_movil

    - name: Analyze code
      run: flutter analyze
      working-directory: aplicativo_movil
      continue-on-error: true


    - name: Run tests
      run: flutter test
      working-directory: aplicativo_movil
