name: TEST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Navigate to aplicativo_movil directory
      run: cd aplicativo_movil

    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - name: Install dependencies
      run: dart pub get
      working-directory: aplicativo_movil  

    - name: Analyze code
      run: dart analyze
      working-directory: aplicativo_movil  

    - name: Run tests
      run: dart test
      working-directory: aplicativo_movil  
